# Generated by Django 4.2.14 on 2024-07-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=300, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
